model_list:
  # Chat Model
  - model_name: lm-studio-model
    litellm_params:
      model: openai/local-model      # Name mappings for LM Studio
      api_base: http://host.docker.internal:1234/v1 # LM Studio default local port
      api_key: "lm-studio"
  - model_name: lm-studio-model
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  
  # Embedding Model
  - model_name: lm-studio-embedding
    litellm_params:
      model: openai/nomic-embed-text
      api_base: http://host.docker.internal:1234/v1
      api_key: "lm-studio"
  - model_name: lm-studio-embedding
    litellm_params:
      model: openai/text-embedding-3-small
      api_key: os.environ/OPENAI_API_KEY

router_settings:
  routing_strategy: usage-based-routing
  redis_host: redis
  redis_port: 6379
  cache_responses: true
